apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: attendance-ingress
  namespace: attendance

spec:
  ingressClassName: nginx

  rules:
    - host: attendance.local

      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: attendance-backend
                port:
                  number: 80

          - path: /
            pathType: Prefix
            backend:
              service:
                name: attendance-frontend
                port:
                  number: 80